# MySQL
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: monologue_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: monologue_test
  pool: 5
  username: root
  password:


# # Postgres
# development:
#   adapter: postgresql
#   host: localhost
#   database: monologue_development
#   username: postgres

# test:
#   adapter: postgresql
#   host: localhost
#   database: monologue_test
#   username: postgres